name: generate data files

on:
  push:
      tags:
        - '*'

jobs:
  fetch:
    if: startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: generate all station data
        run: python main.py
      - uses: actions/upload-artifact@v4
        with:
          name: tmp-data
          path: out/json

  generate-small-files:
    needs: [ fetch ]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tmp-data
          path: out/json
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: generate aral.db
        run: python database.py
      - name: generate fuel.json
        run: python generator.py -ff
      - name: generate facilities.json
        run: python generator.py -f
      - name: generate sitemap.xml
        run: python generator.py -s
      - uses: actions/upload-artifact@v4
        with:
          name: tmp-data-small-files
          path: out/json/other

  generate-ov2:
    needs: [ fetch ]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tmp-data
          path: out/json
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: generate ov2 files
        run: python ov2.py auto
      - uses: actions/upload-artifact@v4
        with:
          name: tmp-data-ov2
          path: out/ov2/

  deploy-cf:
    needs: [ generate-small-files ]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: tmp-data
          path: out/json
      - uses: actions/download-artifact@v4
        with:
          name: tmp-data-small-files
          path: out/json/other
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: run d1.py
        run: python d1.py
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_DATABASE_ID: ${{ secrets.CF_DATABASE_ID }}

  deploy:
    needs: [generate-small-files, generate-ov2]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: tmp-data
        path: out/json
    - uses: actions/download-artifact@v4
      with:
        name: tmp-data-small-files
        path: out/json/other
    - uses: actions/download-artifact@v4
      with:
        name: tmp-data-ov2
        path: out/ov2/
    - name: create github Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: out/
        GITHUB_TOKEN: ${{ secrets.SECRET }}

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.SECRET }}
        publish_dir: out/

  copy:
    needs: [generate-small-files]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: tmp-data-small-files
        path: out/json/other
    - name: Push generated files to https://github.com/aral-preise/aral-prices
      uses: cpina/github-action-push-to-another-repository@main
      env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'out/json/other'
        destination-repository-name: 'aral-prices'
        destination-github-username: 'nickwasused'
        user-email: github.lix1s@simplelogin.co
        target-branch: main
        target-directory: 'data'

  cleanup:
    needs: [deploy, copy]
    permissions:
      actions: write
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v4
        with:
          name: |
            tmp-data
            tmp-data-small-files
            tmp-data-ov2
