name: generate data files

on:
  push:
      tags:
        - '*'

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: generate all station data
        run: python get.py
      - name: generate aral.db
        run: python database.py
      - name: generate fuel.json
        run: python generator.py -ff
      - name: generate facilities.json
        run: python generator.py -f
      - name: generate sitemap.xml
        run: python generator.py -s

  deploy:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: create github Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: out/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: out/

  copy:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: Push generated files to other repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'out/other'
        destination-repository-name: 'aral-prices'
        destination-github-username: 'nickwasused'
        user-email: github.lix1s@simplelogin.co
        target-branch: main
        target-directory: 'data'
